// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SetUsUpBE.Infrastructure.DbContext;

#nullable disable

namespace SetUsUpBE.Infrastructure.DbMigrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526022752_PolishingPhase")]
    partial class PolishingPhase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("SetUsUpBE.Infrastructure.DataEntities.GroupData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasColumnOrder(0);

                    b.Property<string>("CreatorUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("IsUserCreated")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.ToTable("Groups", (string)null);
                });

            modelBuilder.Entity("SetUsUpBE.Infrastructure.DataEntities.GroupMembershipData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasColumnOrder(0);

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupMemberships", (string)null);
                });

            modelBuilder.Entity("SetUsUpBE.Infrastructure.DataEntities.PlaylistData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasColumnOrder(0);

                    b.Property<string>("CreatorUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(512)");

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("GroupId");

                    b.ToTable("Playlists", (string)null);
                });

            modelBuilder.Entity("SetUsUpBE.Infrastructure.DataEntities.PlaylistEntryData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasColumnOrder(0);

                    b.Property<decimal>("BpmChange")
                        .HasColumnType("decimal(8,4)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("CreatorUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<TimeOnly>("End")
                        .HasColumnType("time");

                    b.Property<string>("HexColour")
                        .HasColumnType("varchar(8)");

                    b.Property<long>("Nr")
                        .HasColumnType("bigint");

                    b.Property<Guid>("PlaylistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<TimeOnly>("Start")
                        .HasColumnType("time");

                    b.Property<string>("TransitionToNext")
                        .HasColumnType("varchar(3)");

                    b.Property<bool>("WithPrev")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("PlaylistId");

                    b.HasIndex("SongId");

                    b.ToTable("PlaylistEntries", (string)null);
                });

            modelBuilder.Entity("SetUsUpBE.Infrastructure.DataEntities.PlaylistEntryRatingData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasColumnOrder(0);

                    b.Property<Guid>("PlaylistEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RaterUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlaylistEntryId");

                    b.HasIndex("RaterUserId");

                    b.ToTable("PlaylistEntryRatings", (string)null);
                });

            modelBuilder.Entity("SetUsUpBE.Infrastructure.DataEntities.SongAccessData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasColumnOrder(0);

                    b.Property<string>("CreatorUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SongId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatorUserId");

                    b.HasIndex("GroupId");

                    b.HasIndex("SongId");

                    b.ToTable("SongAccess", (string)null);
                });

            modelBuilder.Entity("SetUsUpBE.Infrastructure.DataEntities.SongData", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("ID")
                        .HasColumnOrder(0);

                    b.Property<string>("Artist")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("Bpm")
                        .HasColumnType("decimal(8,4)");

                    b.Property<decimal>("BpmOut")
                        .HasColumnType("decimal(8,4)");

                    b.Property<TimeOnly>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("InitKey")
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.HasKey("Id");

                    b.ToTable("Songs", (string)null);
                });

            modelBuilder.Entity("SetUsUpBE.Infrastructure.DataEntities.SongSpotifyLinkData", b =>
                {
                    b.Property<Guid>("SongId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SpotifySongId")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("SongId");

                    b.ToTable("SongSpotifyLinks", (string)null);
                });

            modelBuilder.Entity("SetUsUpBE.Infrastructure.DataEntities.SongTagData", b =>
                {
                    b.Property<Guid>("SongId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TagId")
                        .HasColumnType("varchar(7)");

                    b.HasKey("SongId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("SongTags", (string)null);
                });

            modelBuilder.Entity("SetUsUpBE.Infrastructure.DataEntities.TagCategoryData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.ToTable("TagCategories", (string)null);
                });

            modelBuilder.Entity("SetUsUpBE.Infrastructure.DataEntities.TagData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(7)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("TagGroupId")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.HasKey("Id");

                    b.HasIndex("TagGroupId");

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("SetUsUpBE.Infrastructure.DataEntities.TagGroupData", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(5)");

                    b.Property<string>("CategoryId")
                        .IsRequired()
                        .HasColumnType("varchar(3)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("TagGroups", (string)null);
                });

            modelBuilder.Entity("SetUsUpBE.Infrastructure.IdentityExtensions.AppIdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AcceptedLegalVersion")
                        .HasColumnType("int");

                    b.Property<int>("AcceptedSpotifyNoticeVersion")
                        .HasColumnType("int");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayedTagGroupIdsCsv")
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("InstagramAccount")
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("LastDataExportAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("LastInactivityWarningMilestone")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SelectedPlaylistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("ownGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("selectedGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("SelectedPlaylistId");

                    b.HasIndex("ownGroupId")
                        .IsUnique()
                        .HasFilter("[ownGroupId] IS NOT NULL");

                    b.HasIndex("selectedGroupId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("SetUsUpBE.Infrastructure.IdentityExtensions.AppIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("SetUsUpBE.Infrastructure.IdentityExtensions.AppIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SetUsUpBE.Infrastructure.IdentityExtensions.AppIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("SetUsUpBE.Infrastructure.IdentityExtensions.AppIdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SetUsUpBE.Infrastructure.DataEntities.GroupData", b =>
                {
                    b.HasOne("SetUsUpBE.Infrastructure.IdentityExtensions.AppIdentityUser", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatorUser");
                });

            modelBuilder.Entity("SetUsUpBE.Infrastructure.DataEntities.GroupMembershipData", b =>
                {
                    b.HasOne("SetUsUpBE.Infrastructure.DataEntities.GroupData", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SetUsUpBE.Infrastructure.IdentityExtensions.AppIdentityUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SetUsUpBE.Infrastructure.DataEntities.PlaylistData", b =>
                {
                    b.HasOne("SetUsUpBE.Infrastructure.IdentityExtensions.AppIdentityUser", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SetUsUpBE.Infrastructure.DataEntities.GroupData", "Group")
                        .WithMany("Playlists")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatorUser");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("SetUsUpBE.Infrastructure.DataEntities.PlaylistEntryData", b =>
                {
                    b.HasOne("SetUsUpBE.Infrastructure.IdentityExtensions.AppIdentityUser", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SetUsUpBE.Infrastructure.DataEntities.PlaylistData", "Playlist")
                        .WithMany("Entries")
                        .HasForeignKey("PlaylistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SetUsUpBE.Infrastructure.DataEntities.SongData", "Song")
                        .WithMany("PlaylistEntries")
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatorUser");

                    b.Navigation("Playlist");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("SetUsUpBE.Infrastructure.DataEntities.PlaylistEntryRatingData", b =>
                {
                    b.HasOne("SetUsUpBE.Infrastructure.DataEntities.PlaylistEntryData", "PlaylistEntry")
                        .WithMany("Ratings")
                        .HasForeignKey("PlaylistEntryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SetUsUpBE.Infrastructure.IdentityExtensions.AppIdentityUser", "RaterUser")
                        .WithMany()
                        .HasForeignKey("RaterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PlaylistEntry");

                    b.Navigation("RaterUser");
                });

            modelBuilder.Entity("SetUsUpBE.Infrastructure.DataEntities.SongAccessData", b =>
                {
                    b.HasOne("SetUsUpBE.Infrastructure.IdentityExtensions.AppIdentityUser", "CreatorUser")
                        .WithMany()
                        .HasForeignKey("CreatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SetUsUpBE.Infrastructure.DataEntities.GroupData", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SetUsUpBE.Infrastructure.DataEntities.SongData", "Song")
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatorUser");

                    b.Navigation("Group");

                    b.Navigation("Song");
                });

            modelBuilder.Entity("SetUsUpBE.Infrastructure.DataEntities.SongSpotifyLinkData", b =>
                {
                    b.HasOne("SetUsUpBE.Infrastructure.DataEntities.SongData", "Song")
                        .WithOne()
                        .HasForeignKey("SetUsUpBE.Infrastructure.DataEntities.SongSpotifyLinkData", "SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Song");
                });

            modelBuilder.Entity("SetUsUpBE.Infrastructure.DataEntities.SongTagData", b =>
                {
                    b.HasOne("SetUsUpBE.Infrastructure.DataEntities.SongData", "Song")
                        .WithMany()
                        .HasForeignKey("SongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SetUsUpBE.Infrastructure.DataEntities.TagData", "Tag")
                        .WithMany()
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Song");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("SetUsUpBE.Infrastructure.DataEntities.TagData", b =>
                {
                    b.HasOne("SetUsUpBE.Infrastructure.DataEntities.TagGroupData", "TagGroup")
                        .WithMany("Tags")
                        .HasForeignKey("TagGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TagGroup");
                });

            modelBuilder.Entity("SetUsUpBE.Infrastructure.DataEntities.TagGroupData", b =>
                {
                    b.HasOne("SetUsUpBE.Infrastructure.DataEntities.TagCategoryData", "Category")
                        .WithMany("TagGroups")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("SetUsUpBE.Infrastructure.IdentityExtensions.AppIdentityUser", b =>
                {
                    b.HasOne("SetUsUpBE.Infrastructure.DataEntities.PlaylistData", "SelectedPlaylist")
                        .WithMany()
                        .HasForeignKey("SelectedPlaylistId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SetUsUpBE.Infrastructure.DataEntities.GroupData", "OwnGroup")
                        .WithOne()
                        .HasForeignKey("SetUsUpBE.Infrastructure.IdentityExtensions.AppIdentityUser", "ownGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SetUsUpBE.Infrastructure.DataEntities.GroupData", "SelectedGroup")
                        .WithMany()
                        .HasForeignKey("selectedGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("OwnGroup");

                    b.Navigation("SelectedGroup");

                    b.Navigation("SelectedPlaylist");
                });

            modelBuilder.Entity("SetUsUpBE.Infrastructure.DataEntities.GroupData", b =>
                {
                    b.Navigation("Playlists");
                });

            modelBuilder.Entity("SetUsUpBE.Infrastructure.DataEntities.PlaylistData", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("SetUsUpBE.Infrastructure.DataEntities.PlaylistEntryData", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("SetUsUpBE.Infrastructure.DataEntities.SongData", b =>
                {
                    b.Navigation("PlaylistEntries");
                });

            modelBuilder.Entity("SetUsUpBE.Infrastructure.DataEntities.TagCategoryData", b =>
                {
                    b.Navigation("TagGroups");
                });

            modelBuilder.Entity("SetUsUpBE.Infrastructure.DataEntities.TagGroupData", b =>
                {
                    b.Navigation("Tags");
                });
#pragma warning restore 612, 618
        }
    }
}
